micronaut:
  application:
    name: demo

datasources:
  default:
    url: url:jdbc:mysql://localhost:3306/exam
    driverClassName: com.mysql.jdbc.Driver
    username: sa
    password: ''
    dialect: Mysql